server.port=${PORT:8080}

spring.datasource.url=${mysql://root:CyRZyZzPsCoSznSnqWbHSnLVVpyBKfzZ@maglev.proxy.rlwy.net:25873/railway}
spring.datasource.username=${root}
spring.datasource.password=${CyRZyZzPsCoSznSnqWbHSnLVVpyBKfzZ}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
